export const CHECKIN_VEHICLE = "CHECKIN_VEHICLE";
export const CHECKOUT_VEHICLE = "CHECKOUT_VEHICLE";
export const FETCH_VEHICLE = "FETCH_VEHICLE";
export const FETCH_VEHICLES = "FETCH_VEHICLES";
export const ADD_CATEGORY = "EDIT_CATEGORY";
export const EDIT_CATEGORY = "EDIT_CATEGORY";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";